### ISSUE TITLE
Do the number of zeros passed to new() matter?

### ISSUE THREAD

**Issue by 9mm** [ericmj/decimal#111]
I notice that this decimal library 'remembers' trailing zeros, which is concerning to me, in that I just want to make 100% sure I know how it works.

By storing that information, its kind of implying (to me) that it needs it for some reason (as opposed to just truncating to whatever I pass in (`0.20000` becomes `0.2`), which basically could be some kind of hidden gotcha about rounding errors or 'built in precision' into the decimal, rather than just inherent "this will always be right give us any data you want and we will always make sure its normalized and perfect as far as precision is concerned". now this is a decimal library so I cant imagine that ever being wrong, I just wanted to make 100% sure that the number of trailing zeros will 100% not affect a proper math outcome that is exact (like if output precision is greater than the precision passed in). thanks!

**Comment by 9mm** [comment]
Follow up question: what method is best for `to_string` if I simply want the number to appear as `x.xxx` (no exponent/power signs or anything weird like that). This is for price data so it should be formatted exactly as `30.000000142948` without any weird symbols in it. I was thinking `:normal` but when I try all the different modes it has the same output for the stuff I enter, so I want to make sure I pick the right one. thanks

**Comment by ericmj** [comment]
The library maintains trailing zeros but they do not affect the arithmetic operations since all operations work with the full precision up to the maximum precision defined in the context.

The `:normal` option will print without an exponent. If you want to remove trailing zeros you can call `Decimal.reduce/1` on the number.

**Comment by 9mm** [comment]
awesome thanks
