### ISSUE TITLE
Could we bump the version and push a release to hex?

### ISSUE THREAD

**Issue by eqmvii** [ericmj/decimal#120]
Could we get a small update with these recent changes:  https://github.com/ericmj/decimal/pull/116 
pushed/released to hex.pm? 

It would simplify things for a series of dependency upgrades we're working on in our production elixir application. Otherwise we will have to point at forks/commits temporarily, which we'd prefer to avoid.

Thanks, and let me know if there's anything I can do to help!

**Comment by ericmj** [comment]
We have done some API changes that we are still not sure if we are going to include in the final release, so we are holding off on publishing until we are sure.

**Comment by eqmvii** [comment]
Appreciate the info, thanks!

**Comment by ericmj** [comment]
Released
