### ISSUE TITLE
Decimal.new allows for "-0" value

### ISSUE THREAD

**Issue by elbow-jason** [ericmj/decimal#15]
```elixir
iex(4)> Decimal.new("-0")                   
#Decimal<-0>
iex(5)> Decimal.new("-0") < Decimal.new("0")
true
iex(6)> Decimal.new("-0") > Decimal.new("0")
false
```

Additionally, neg zero is less than positive zero.

**Comment by ericmj** [comment]
The specification allows for the `-0` number and `-0` is ordered lower than `0`. See http://speleotrove.com/decimal/damisc.html#refcotot
