### ISSUE TITLE
How to specify scale?

### ISSUE THREAD

**Issue by apeacox** [ericmj/decimal#16]
Hi there, thank you for this very useful package :-)

As stated in the title, I'd need to specify a scale for Decimal(s), but I didn't found a way to do it :-/

The problem arised when I was writing tests to check some values from database, sometimes they fail because of scale. Here's a quick example of the errors I get:

```
test update_line_item_quantity/3 updates line_item quantity and updates order total (Nova.Commands.OrderCommandsTest)
     test/commands/order_commands_test.exs:40
     Assertion with == failed
     code: order.total() == new_price
     lhs:  #Decimal<41.00>
     rhs:  #Decimal<41.0>
```

perhaps I'm doing something wrong.

thank you in advance for an eventual reply :-)

**Comment by ericmj** [comment]
A scale cannot be set. You have to use `Decimal.compare/2`, I plan to add comparison convenience functions because I understand that `compare/2` can be annoying to use.

**Comment by apeacox** [comment]
Thanks! didn't noticed that function, my fault :-P I'm going to fix my tests with that :-)
