### ISSUE TITLE
Feature request Decimal.approx?/3

### ISSUE THREAD

**Issue by warmwaffles** [ericmj/decimal#169]
I have a need to compare two decimals to see if they are within an epsilon range.

```elixir
Decimal.approx?(Decimal.new("1.66666667"), Decimal.new("1.67"), Decimal.new("0.01"))
```

**Comment by ericmj** [comment]
We are trying to limit the scope of this library. I feel this function would not be used enough to warrant being added since you can do the same operation with existing functions.

Thanks for the suggestion!
