### ISSUE TITLE
Proposal: Change the Inspect protocol implementation

### ISSUE THREAD

**Issue by Adzz** [ericmj/decimal#175]
When I a Decimal outputted to the console it looks like this:

```elixir
#Decimal<1>
```

This is fine and all but makes copy / pasting from the terminal a nightmare as the above isn't valid elixir code. Other structs handle this by having a sigil - Date for example. That means you can output `"~D[2020-01-01]"`

Would it be possible to change the inspect protocol to instead output this:

```elixir
Decimal.new("1")
```

Or have some other way to make this better. I know the idea of a Decimal sigil has been rejected before -is there any movement on that? I know Decimal even uses a [sigil in its tests ](https://github.com/ericmj/decimal/blob/master/test/test_helper.exs)

**Comment by Adzz** [comment]
Nice! I'd be happy to try it for sure.

**Comment by Adzz** [comment]
https://github.com/ericmj/decimal/pull/176

**Comment by Adzz** [comment]
Hey 👋  Are there any plans to do a release for this?

**Comment by ppraisethesun** [comment]
Elixir 1.14 is moving towards expression based inspects, so it would be a good time to release this
