### ISSUE TITLE
proposal: `gte?/2` and `lte?/2`

### ISSUE THREAD

**Issue by Mazuh** [ericmj/decimal#204]
**suggestion:** a sugar for "greater than or equal to" as `gte?/2` and "less than or equal to"  as `lte?/2`

of course I'm not just asking, I can implement these helpers by myself relying on existing functions, add tests and open a pull request... but I'm asking beforehand just to understand the context behind the absence of these functions, they're somewhat common for decimal structures implementations on other stacks.

my point is: if I open a proper PR adding these functions, will it be considered or just denied by design?

**Comment by ericmj** [comment]
Please make a PR.

**Comment by Mazuh** [comment]
thanks for replying, @ericmj , I just opened it 😄

**Comment by APB9785** [comment]
@ericmj @wojtekmach can we get a new release for this?  The 2.1.1 docs now show `gte?/2` and `lte?/2` as available in the public API, but they're actually missing and will lead to a compile error when used.

**Comment by wojtekmach** [comment]
Yes I’ll release this soon. I published docs from main for unrelated reason and didn’t realize it would obviously document unreleased functions. Thanks for the remainder!

**Comment by wojtekmach** [comment]
Hey, sorry, we'd need some more work done towards a new release (a gte?/3 and lte?/3) so I made sure latest docs align with the released version, thank you again for spotting this.
