### ISSUE TITLE
Scientific notation on very small numbers

### ISSUE THREAD

**Issue by darksheik** [ericmj/decimal#25]
Noticing that very small numbers that have significant zeroes at the end seem to jump to scientific notation when passed through the round function:

```
iex(27)> Decimal.new("80")
#Decimal<80>
iex(26)> Decimal.new("80") |> Decimal.round(2) |> to_string  
"8E+1"
```

Is there any way to control this, or at least have to_string represent the full number?
Thanks!

**Comment by ericmj** [comment]
Pass `:normal` to `to_string`. https://hexdocs.pm/decimal/Decimal.html#to_string/2
