### ISSUE TITLE
Why is there no Decimal.to_float ?

### ISSUE THREAD

**Issue by Qqwy** [ericmj/decimal#28]
Today, someone asked about this in the Elixir slack group, and I've found myself wondering about this earlier.

There exists `Decimal.to_integer` and `Decimal.to_string`, but there is no `Decimal.to_float`. There are some libraries that only take floats as their input. (an example: [currency_formatter](https://github.com/smeevil/currency_formatter) )

Why is there no Decimal.to_float? Is there another suggested way to do this type of lossy Decimal -> Float conversion?

**Comment by ericmj** [comment]
> Why is there no Decimal.to_float? Is there another suggested way to do this type of lossy Decimal -> Float conversion?

No, and that's the reason why there is no `to_float` function. I don't know at the top of my head the best way to do this conversion. If you know, feel free to send a PR.

**Comment by aghosh47** [comment]
can there be not .to_float/2 where first argument is the decimal and second id precision

**Comment by Qqwy** [comment]
@ericmj What problem is there with the naïve approach?

```
d = Decimal.new(1.23456789)
f = d.coef * :math.pow(10, d.exp) * d.sign
```

The only 'problem' here is that the the rounding tries to be more exact than the original decimals, so we end up with a float like `1.2345678900000001` or `1.234567999999999999`.

Another approach would be

```
d = Decimal.new(1.23456789)
f = List.to_float(Decimal.to_string(d) |> String.to_charlist)
```

This does not have above issue, but of course the string -> charlist -> float conversion has multiple steps that make this approach much slower.

Hmm...

**Comment by ericmj** [comment]
> The only 'problem' here is that the the rounding tries to be more exact than the original decimals, so we end up with a float like 1.2345678900000001 or 1.234567999999999999.

That's quite a big problem for a library whose whole purpose is to provide exact decimal arithmetic.

> This does not have above issue, but of course the string -> charlist -> float conversion has multiple steps that make this approach much slower.

You can do this right now without  `Decimal.to_float`. You can also look at the erlang implementation of that function and see if you can repurpose it to work for decimals.

**Comment by Qqwy** [comment]
I have so far been unable to find the source of  `List.to_float`.

As for the first approach: This problem of having 'too much' exactness can be mitigated as follows:

```
d = Decimal.new(12.3456789)
f = d.sign * :math.pow(10, d.exp) * d.coef |> Float.round(min(-d.exp, 15))
```

**Comment by ericmj** [comment]
Unfortunately your proposal does not work correctly for all possible values either. If I knew the solution I would implement it myself, but I don't. I suggest reading through the specifications linked in the documentation and reading up on IEEE 754 floating point arithmetic.

If the solution above works for you then that's great, you can use it in your application code. But I am not going to add a potentially buggy implementation if you cannot show me why it will work correctly for all possible values.

**Comment by Qqwy** [comment]
Yes, above solution only works as long as the value is not `NaN` or `+-Infinity`. I will read up on the IEEE 754 standard and implement a proper solution, which I'll create a Pull-Request for.

One remaining problem with this is that Erlang does not follow the IEEE standard with relation to Infinity: Infinity is not an allowed value for floats in Erlang, and overflow (or things like `1.0 / 0.0`) will result in an error instead. Oddly enough, Erlang does support `NaN`, although I have yet to find a math operation that returns it.

Maybe the nicest way to mitigate this would be to give the final choice (raising when passed infinity, vs returning for instance the symbol `:infinity` instead of a float) to the end user with an optional parameter.

**Comment by ericmj** [comment]
There are other issues as well. After playing around with it a bit I could produce the following number that can be expressed as a float but not converted from a decimal:

```elixir
iex(8)> 0.12345678912345678
0.12345678912345678
iex(9)> fun.(Decimal.new(0.12345678912345678))
0.123456789123457
```

You will not get exact values when using `:math.pow/2`.

**Comment by ericmj** [comment]
I can also make it crash on some values:

```elixir
iex(12)> Decimal.new(12300) |> Decimal.reduce |> fun.()
** (FunctionClauseError) no function clause matching in Float.round/2
    (elixir) lib/float.ex:163: Float.round(1.23e4, -2)
```

**Comment by Qqwy** [comment]
The first problem (`fun.(Decimal.new(0.12345678912345678))` =/= `0.123456789123457`) is because `Float.round/1` takes a number between 0 and 15 decimal positions. On 32-bit systems, this makes sense (or does it? 'normal' 32-bit floats have 24 decimals of mantissa precision. Maybe the floats of historic Erlang systems had even lower precision...). On 64-bit systems, floats can have more precision, but Erlang's float rounding implementation does not allow this.

So I would argue that this is 'expected behaviour'.

As for the second issue: I did not know about `Decimal.reduce/1`. Adapting the function to handle this is of course trivial, by preventing the rounding lower than zero.

```
f = fn d -> 
rounding_factor = min(max(0, -d.exp), 15)
d.sign * :math.pow(10, d.exp) * d.coef |> Float.round(rounding_factor)
```

I'll create a PR for this, and we can discuss it further there. :-)

**Comment by ericmj** [comment]
> On 32-bit systems, this makes sense (or does it? 'normal' 32-bit floats have 24 decimals of mantissa precision.

I think you are confusing binary and decimal digits.

> So I would argue that this is 'expected behaviour'.

I wouldn't say so. Why are there numbers we can express with floats that we cannot convert to from decimals?

> I'll create a PR for this, and we can discuss it further there.

I need some more convincing this produces correct behaviour before I would merge a PR. Again, I would suggest looking at similar implementations, such as `:erlang.list_to_float/1`.
