### ISSUE TITLE
Incorrect results with Decimal.div_rem/2

### ISSUE THREAD

**Issue by iain** [ericmj/decimal#29]
I am starting to doubt myself, but the output of `Decimal.div_rem/2` (and its related methods) makes no sense to me.

Example:

``` elixir
iex> Decimal.div_rem(Decimal.new("88"), Decimal.new("1.00"))
{#Decimal<80>, #Decimal<80>}
```

I am expecting `{80,#Decimal<0>}`

Here is illustration of the weird effect of precision in the second argument.

``` elixir
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new(1))
{#Decimal<1>, #Decimal<0.000>}
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new("1.0"))
{#Decimal<1>, #Decimal<4.00>}
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new("1.00"))
{#Decimal<1>, #Decimal<34.0>}
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new("1.000"))
{#Decimal<1>, #Decimal<234>}
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new("1.0000"))
{#Decimal<1>, #Decimal<2340>}
iex> Decimal.div_rem(Decimal.new("1.234"), Decimal.new("1.00000"))
{#Decimal<1>, #Decimal<23400>}
```

I would expect `{1, #Decimal<0.234>}` as outcome for all of them.

**Comment by ericmj** [comment]
Definitely seems to be wrong and there also seems to be no tests for this function.

A PR would be very appreciated as I am and will be busy over the next few weeks. Thanks for the report!
