### ISSUE TITLE
1.0 is not equal to 1

### ISSUE THREAD

**Issue by obmarg** [ericmj/decimal#34]
I'm not sure whether this is expected behaviour, but 

```elixir
iex(1)> Decimal.new("1.0") == Decimal.new("1")
false
```

I'm running into this when trying to get sqlite_ecto running against the latest ecto integration tests.  Sqlite takes 1.0 and simplifies it into 1, so when the Decimal value is read from the database it doesn't compare equal to the value that was put into the database.

**Comment by ericmj** [comment]
Use `Decimal.equal?/2` instead.
