### ISSUE TITLE
still inconsistent rounding ?

### ISSUE THREAD

**Issue by awetzel** [ericmj/decimal#35]
```
iex(2)> Decimal.new(1,5,-4) |> Decimal.round(0)
#Decimal<1>
```

This does not seems quite right ? what do you think ? round(0.0005) == 0

**Comment by ericmj** [comment]
Seems to be wrong indeed.

**Comment by jesenko** [comment]
Rounding for specified case `Decimal.new(1,5,-4) |> Decimal.round(0)` still returns `#Decimal<1>` in `v1.3.1`.

**Comment by kelostrada** [comment]
Can we expect a release for this fix? It still bugged in a newest version on Hex
