### ISSUE TITLE
Decimal.to_string with default type :normal

### ISSUE THREAD

**Issue by sunprophit** [ericmj/decimal#36]
3rd party libraries (like Poison) encode Decimal as string in scientific notation, because to_string() default type is :scientific. Any options to change this behaviour for all to_string calls?

**Comment by ericmj** [comment]
Changing the default type would be a breaking change so unless we find more things we want to change I am bit hesitant.

It would be easy for Poison and other libraries to pass the `:normal` argument.

**Comment by sunprophit** [comment]
Isn't context a suitable place to redefine this behaviour? It would be back-compatible change

**Comment by ericmj** [comment]
The context is used for operations on numbers that return new numbers, it is not applicable to a function like `Decimal.to_string`.

This is just a single function call so I don't see the problem with just adding the extra argument.

**Comment by sunprophit** [comment]
It's single function call in 3rd party library. It would be ok if scientific notation would be common way to represent decimal as a string.

**Comment by ericmj** [comment]
I'm sorry if it's not OK to you but it is a common way to represent a decimal as a string. It is also following the IEEE 754 specification that this library adheres to so it's unlikely to change.

I will consider changing this for the 2.0 version but that version is not planned yet so I would instead suggest to fix the 3rd party library.
