### ISSUE TITLE
New bug-fix release

### ISSUE THREAD

**Issue by jesenko** [ericmj/decimal#42]
Would it be possible to release 1.3.2 in near future? There have been some quite significant bug fixes in master since last release. 

Using currently released version might lead to some quite subtle bugs in apps using this library (e.g. wrong rounding on some edge cases)

**Comment by kurayama** [comment]
Any news on this? I'm also getting rounding issues in a project and for now I have to use master.

**Comment by ericmj** [comment]
Released 1.4.0.
