### ISSUE TITLE
Unexpected errors for infinities in comparisons

### ISSUE THREAD

**Issue by alvinlindstam** [ericmj/decimal#43]
## adding and subtracting infinities
The docs for `Decimal.add/2` and `Decimal.sub/2` both states that *If one number is -Infinity and the other +Infinity :invalid_operation will be signalled*. Based on this, I would expect it to be possible to add or subtract to infinities if they hade the same sign. That does however throw the same error

```elixir
iex(1)> positive_infinity = Decimal.new(1, :inf, 1)
#Decimal<Infinity>
iex(2)> negative_infinity = Decimal.new(-1, :inf, 1)
#Decimal<-Infinity>
iex(3)> Decimal.add positive_infinity, negative_infinity 
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
iex(3)> Decimal.add positive_infinity, positive_infinity
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
```

**Should this be solved by a documentation update, or should we enable to infinities on the same side to be added/subtracted?** If we should allow it, what would be the correct new exponent?

## Comparing infinities
There is no documentation for infinity values in `Timex.cmp/2`, `Timex.compare/2` or `Timex.equal/2`, so I would expect them to work for two infinities. However, since they all use `Timex.add/2` in the end, they will fail.

```elixir
iex(3)> Decimal.compare positive_infinity, negative_infinity
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
    (decimal) lib/decimal.ex:317: Decimal.compare/2
iex(3)> Decimal.compare positive_infinity, positive_infinity
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
    (decimal) lib/decimal.ex:317: Decimal.compare/2
iex(3)> bigger_positive_infinity = Decimal.add positive_infinity, Decimal.new(10)
#Decimal<Infinity>
iex(4)> Decimal.compare positive_infinity, bigger_positive_infinity
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
    (decimal) lib/decimal.ex:317: Decimal.compare/2
iex(4)> Decimal.equal? positive_infinity, bigger_positive_infinity
** (Decimal.Error) : (+-)Infinity + (+-)Infinity
    (decimal) lib/decimal.ex:271: Decimal.add/2
    (decimal) lib/decimal.ex:317: Decimal.compare/2
    (decimal) lib/decimal.ex:346: Decimal.equal?/2
```
I would expect -Infinity to be less that +Infinity. But what would be the correct comparison of two infinities with different exponents? It seems that `mult/2` multiplies the exponent when two infinities are multiplied, while `sub/2` and `add/2` simply ignores the non infinite argument.

----
I am using Decimal 1.3.1, but there does not seem to be any related changed to master since.

**Comment by ericmj** [comment]
> adding and subtracting infinities

The documentation is correct and the code should be fixed. The specification makes no special mention of adding or subtracting infinities of the same sign so it should behave as you expect.

> Comparing infinities

The code should be fixed and should behave as you said.

> But what would be the correct comparison of two infinities with different exponents? It seems that mult/2 multiplies the exponent when two infinities are multiplied, while sub/2 and add/2 simply ignores the non infinite argument.

They should compare equal.

**Comment by alvinlindstam** [comment]
I'll submit at PR
