### ISSUE TITLE
Sorting enumerables of decimals

### ISSUE THREAD

**Issue by Qqwy** [ericmj/decimal#45]
To my knowledge, there is not a good way to sort an enumerable filled with decimals.

The `Enum` module exposes `Enum.sort` and `Enum.sort_by`.

Naïvely using `Enum.sort/1` on a list of Decimals will of course go wrong, because the Decimal structs are then sorted by Erlang's built in term order, which means that the map fields are compared. This results in wrong answers, as there are multiple Decimal struct representations of the same number, as well as for instance the `coef` field being compared before the `sign` field.

Now, Decimal exposes both `Decimal.cmp/2` and `Decimal.compare/2`, which could be passed as second argument to `Enum.sort/2`.

However, `Decimal.compare/2` returns itself a decimal (0, 1 or -1), giving rise to the same problems as above.

`Decimal.cmp/2` on the other hand returns (`:lt`, `:gt` or `:eq`). In Erlangs built-in term ordering, these would however, from low to high, be ordered (`:eq`, `:gt`, `:lt`), and therefore insufficient.

The only current 'approach' I can think of is to use `Enum.sort_by(enumerable, &Decimal.to_float/1)`. This does not feel good, because we use the precision we are using decimals for in the first place.

----

I therefore think that the Decimal library would benefit from an additional comparison function that returns either:

- (-1, 0, 1) (as integers) during comparison. Or alternatively:
- `:<`, `:=`, `:>` (the atoms). These are in the correct order, per the ASCII table definition.

Maybe it is possible to vary what result is given back by adding an optional third parameter to either `Decimal.cmp` or `Decimal.compare` (or both, as the functions also have different treatment of NaN values).

And maybe there is another, better way. In any case, I think this is a use-case common enough to discuss.

**Comment by ericmj** [comment]
I don't think we should have three comparision functions in the library. You can use ` Enum.sort(enum, &(Decimal.cmp(&1, &2) != :gt))` instead.

**Comment by Qqwy** [comment]
You are right. Yet another comparison function is not the solution. I was led astray by the documentation of `Enum.sort`, but it actually does not care about term ordering at all. Instead, it just wants you to pass a function that returns `true` for all terms that can be considered less or equal to another.

I do wonder why the following do not exist, however:

- `Decimal.lt?/2`. Right now: `Decimal.cmp(a, b) == :lt)`
- `Decimal.lte?/2`. Right now: `Decimal.cmp(a, b) != :gt)`
- `Decimal.equal?/2`. Right now: `Decimal.cmp(a, b) == :eq)`
- `Decimal.gte?/2`. Right now: `Decimal.cmp(a, b) != :lt)`
- `Decimal.gt?/2`.Right now: `Decimal.cmp(a, b) == :gt)`
- `Decimal.zero?/1` (Very useful to prevent division-by-zero checks). Right now: `Decimal.cmp(a, Decimal.new(0)) == :eq)`

I think adding these would make code of people that use the library a lot more readable and user-friendly.

**Comment by ericmj** [comment]
Adding `Decimal.zero?/1` might be useful but I don't agree the other functions should be added. This library implements the IEEE754 spec and adds some additional convenience functions, such as `Decimal.cmp/2`. But I don't think adding 6 functions that saves a few a character's fits with the goals of this library. Decimal focuses on having a correct implementation of IEEE754, more general purpose math libraries that focuses on API can be built on top of Decimal.

**Comment by Qqwy** [comment]
I would greatly value the addition of the comparison operations, because I think that `Decimal.lte(foo, bar)?` or `Decimal.less_than_or_equal?(foo, bar)` is a lot more clear in intent than `Decimal.compare(foo, bar) != :gt`, which requires readers of the code to mess with low-level implementation details.

However, I apologize for having misunderstood the purpose of the Decimal library. As the library's description only states 'Arbitrary precision decimal arithmetic for Elixir', I expected that the approach was to create a library to be directly used by an applications programmer (where the ability to specify clear intent is very important), rather than a library that tightly wraps the IEEE754 specification and should just be used as a component of a more high-level math library (where adhering to the spec is very important).

I understand that you want to keep the API as lightweight as possible. I have one request for you:

Could you make it more clear that Decimal is meant to be a tight implementation of the IEEE754 specification, rather than a full-featured library to work with infinite-precision decimal numbers? After starting to look for it, I found a reference to IEEE854-1987 in the Decimal module documentation, but adapting the Hex.pm description and adding a section to the `README.md` might be possibilities for improving clarity.

Thank you for your hard work! :slightly_smiling_face:

**Comment by ericmj** [comment]
> which requires readers of the code to mess with low-level implementation details.

What's the low-level implementation detail? Would `Decimal.compare(foo, bar) in [:lt, :eq]` make more sense?

> I expected that the approach was to create a library to be directly used by an applications programmer (where the ability to specify clear intent is very important)

It can be used by application programmers, I think we just have different ideas what clear intent is. Why add five functions that directly call a more powerful function and they only save a few characters? Having a small, powerful API is usually better than having a large API with many redundant functions. This is also following Elixir's standard library's conventions, which has five `compare/2` functions would it make sense to add 25 extra functions for them?

> Could you make it more clear that Decimal is meant to be a tight implementation of the IEEE754 specification, rather than a full-featured library to work with infinite-precision decimal numbers? After starting to look for it, I found a reference to IEEE854-1987 in the Decimal module documentation, but adapting the Hex.pm description and adding a section to the README.md might be possibilities for improving clarity.

What is a full-featured library? I wouldn't want to use a library that implements every feature imaginable. I am happy with the current description and documentation of the specs the library follows.
