### ISSUE TITLE
Precision isn't set properly?

### ISSUE THREAD

**Issue by robotvert** [ericmj/decimal#47]
Hi there,

I might be using the library wrong but I've come across an extremely confusing case where I have a phoenix service with a PG DB and 2 columns of :decimal type, "height" and "width".
When I pull the associated record and try to change the precision to do some calculations, for some reason the precision is 2 places off:

```elixir
D.get_context
# => %Decimal.Context{flags: [], precision: 28, rounding: :half_up, traps: [:invalid_operation, :division_by_zero]}

x = D.mult(line.height, line.width)
# => #Decimal<8.1000>

D.with_context(%D.Context{precision: 2}, fn -> D.mult(x, D.new(2)) end)
# => #Decimal<16>

D.with_context(%D.Context{precision: 4}, fn -> D.mult(x, D.new(2)) end)
# => #Decimal<16.20>
```

Am I missing something?
I'm not sure who might be the culprit here, this library, ecto, postrgrex..??

Thanks!

**Comment by ericmj** [comment]
Precision is the number of significant digits that will be returned from an operation. See the tables here for examples of precision: https://en.wikipedia.org/wiki/Significant_figures#Rounding_and_decimal_places.

If you want to change the number of digits before or after the decimal point you need to use `Decimal.round`.

**Comment by robotvert** [comment]
Right, I mistook it for the scale.

IMHO though the example about the precision in the README is kind of confusing, e.g. 1 / 3 yielding 0.33 with a precision of 2 is indeed correct but might lead to misunderstandings such as mine.
How about an example such as this one instead?
```elixir
iex> D.set_context(%D.Context{D.get_context | precision: 9})
:ok
iex> D.div(D.new(100), D.new(3))
#Decimal<33.3333333>
iex> D.set_context(%D.Context{D.get_context | precision: 2})
:ok
iex> D.div(D.new(100), D.new(3))
#Decimal<33>
```

Thanks for the swift reply, closing this non issue.

**Comment by ericmj** [comment]
That's a way better example, would you mind fixing it in the docs? Thank you!

**Comment by robotvert** [comment]
Done => https://github.com/ericmj/decimal/issues/48

I'm not sure how the docs are updated on hexdocs though, anything special to do?

**Comment by ericmj** [comment]
> They will be updated when the next release to Hex is made.
