### ISSUE TITLE
Compile warnings on deprecated `Integer.to_char_list/1` on Elixir 1.5.0-rc.0

### ISSUE THREAD

**Issue by kipcole9** [ericmj/decimal#49]
Three warnings on Elixir 1.5.0-rc.0:
```
warning: Integer.to_char_list/1 is deprecated, use Integer.to_charlist/1
  lib/decimal.ex:944

warning: Integer.to_char_list/1 is deprecated, use Integer.to_charlist/1
  lib/decimal.ex:963

warning: Integer.to_char_list/1 is deprecated, use Integer.to_charlist/1
  lib/decimal.ex:986
```
I'm happy to send a PR if that's acceptable.

**Comment by ericmj** [comment]
I'm hesitant to bump the Elixir version requirements just to fix warnings when there is no other reason to bump the requirement.

Can you send a PR that does conditional compilation based on the current elixir version. Like this: https://github.com/hexpm/hex/blob/master/lib/hex.ex#L44-L52

**Comment by ericmj** [comment]
Ping.
