### ISSUE TITLE
Sqrt?

### ISSUE THREAD

**Issue by Fredeli** [ericmj/decimal#50]
Hey,

is it correct, that the module does not implement the square root for Decimal? I am using it to calculate pi with arbitrary precision using the Gauss–Legendre algorithm(https://en.wikipedia.org/wiki/Gauss%E2%80%93Legendre_algorithm).

Thanks

**Comment by ericmj** [comment]
That is a correct. We need an algorithm for calculating an exact square root for the given precision in the context. This is up for grabs by contributors.

**Comment by ericmj** [comment]
Sorry no. Research is needed first to find a correct and appropriate algorithm.
