### ISSUE TITLE
Expose `coef/1`, `sign/1` and `exp/1` functions

### ISSUE THREAD

**Issue by Qqwy** [ericmj/decimal#56]
I have a small feature request: exposing methods that return the coefficient, sign and exponent of a given Decimal number.

Right if you want to find out these fields of the number, you'll have to perform pattern matching of the struct. This is possible, but bad, because the internal structure of Decimal is a private/hidden implementation detail and might possibly change in the future.

Why does someone need access to these fields? 
To perform lossless conversions to different types of data structures.

**Comment by lexmag** [comment]
👍 but I think if we need to expose those fields it would be better to make `Decimal` struct public (at least partially public via docs, something similar we do in `Macro.Env` IIRC), otherwise fields hiding and such functions feel artificial to me.

**Comment by wojtekmach** [comment]
The struct is public, see issue and associated pr: https://github.com/ericmj/decimal/issues/19

**Comment by Qqwy** [comment]
In that case, pattern matching is of course just fine :-).
