### ISSUE TITLE
ecto thinks value is always changing

### ISSUE THREAD

**Issue by atomkirk** [ericmj/decimal#75]
We have a `:decimal` field in our schema and ecto changesets always mark it as changing even though its not. I assume this is because ecto is trying to compare the Decimal structs and not seeing them as equal?

**Comment by ericmj** [comment]
That is possible, but hard to say without seeing the values or the code. This is more of an Ecto question than Decimal though.

**Comment by atomkirk** [comment]
Well that depends. If, like swift, elixir has something like an equatable protocol that decimal is not using, then its a Decimal question. Otherwise, yeah, ecto needs to provide a way to customize comparing of values for changes and then decimal needs to implement it.

**Comment by ericmj** [comment]
All of it would have to be implemented in Ecto since Decimal does not know about Ecto.

**Comment by atomkirk** [comment]
Oh i see. I thought decimal supported ecto, but its ecto that explicitly supports decimal

**Comment by ericmj** [comment]
Please open an issue on Ecto.
