### ISSUE TITLE
Decimal matching in function arguments and guard clauses

### ISSUE THREAD

**Issue by jordan-brough** [ericmj/decimal#80]
I'd like to be able to write something like this:
```elixir
def capture_funds(account, 0), do: {:error, :invalid_amount}
def capture_funds(account, amount) do
  # …
end
```
But my `amount` is a `Decimal`.  Is there any way to support this?

Would it be reasonable to write:
```elixir
def capture_funds(account, %Decimal{sign: 1, coef: 0}), do: {:error, :invalid_amount}
```
?
Is the structure of `Decimal` something that we can depend on externally?

Similarly, would it be reasonable to write:
```elixir
def capture_funds(account, %Decimal{sign: 1, coef: coef} = amount) when coef > 0 do
  # …
end
```
?

**Comment by jordan-brough** [comment]
Similarly, would it be reasonable to write:
```elixir
def capture_funds(account, %Decimal{sign: 1, coef: coef}) when coef > 0, do
  # …
end
```
?

**Comment by ericmj** [comment]
Yes, you can depend on the structure but it's very tricky, only works for certain checks and it's easy to make mistakes.

For example if you want to match against a zero number you have to match on `%Decimal{coef: 0}`, including the sign like you did would not always work.

Because of this we recommend using the equality and comparison functions instead, `equal?/2`, `cmp/2`, etc.

**Comment by jordan-brough** [comment]
Thank you for the reply @ericmj!

If I stick to `%Decimal{coef: 0}` and constrain myself to checking for zero-values then I should be safe, right? Checking for `0` alone is sufficiently handy that I'd be tempted to do that.

Is there any hope of `Decimal` being able to be compared to other numbers, and used in matching in a nice way?  By some addition to Elixir or even Erlang?  From my reading of https://elixirforum.com/t/comparison-of-decimals-not-logical/770/7 it sounds unlikely?
It's too bad since we have `Decimal`s all over our codebase and often have to break out of standard Elixir styles to handle them.

**Comment by ericmj** [comment]
> If I stick to %Decimal{coef: 0} and constrain myself to checking for zero-values then I should be safe, right? Checking for 0 alone is sufficiently handy that I'd be tempted to do that.

Yes, it should be okay to pattern matching for a zero value.

> Is there any hope of Decimal being able to be compared to other numbers, and used in matching in a nice way?

No, it would probably require changes to Erlang and the VM.

**Comment by jordan-brough** [comment]
Thanks very much for the replies and info.
