### ISSUE TITLE
to_float issue with long decimal precision

### ISSUE THREAD

**Issue by tyler40AU** [ericmj/decimal#82]
The following code gives 0.5, and seems to be an issue any time there are 17 or more 9s.

iex(8)> Decimal.to_float(Decimal.new("0.9999999999999999"))
0.9999999999999999
iex(9)> Decimal.to_float(Decimal.new("0.99999999999999999"))
0.5

Other numbers seem to be okay
iex(23)> Decimal.to_float(Decimal.new("0.8888888888888888888888"))
0.8888888888888888

Here is my context
iex(22)> Decimal.get_context
%Decimal.Context{flags: [], precision: 28, rounding: :half_up,
 traps: [:invalid_operation, :division_by_zero]}

**Comment by ericmj** [comment]
Fixed in #83.
