### ISSUE TITLE
Smart assertion

### ISSUE THREAD

**Issue by IcyEagle** [ericmj/decimal#94]
I wonder if it's possible to teach ExUnit to do smart assertion over Decimal values.
In fact I'd like to get it works:
```elixir
assert %{foo: Decimal.new(1)} == %{foo: Decimal.new(1.0)}
```
I understand that Decimals internal representation may differ but it's really annoying me to use pattern matching and Decimal.equal?/2 for that:
```elixir
assert %{foo: foo} = %{foo: Decimal.new(1.0)}
assert Decimal.equal?(foo, Decimal.new(1))
```

Using operator ==/2 overriding it's possible to fix comparison for plain structs like `Decimal.new(1) == Decimal.new(1.0)`, but it doesn't work with structs like Map, List etc.

Any ideas about that?

**Comment by wojtekmach** [comment]
@IcyEagle tricky stuff! (e.g. https://github.com/elixir-ecto/ecto/issues/2473)

even if we override `==/2` to use `Decimal.equal?/2` (see below), there are other parts of ExUnit that won't quite work well e.g. diffs (which rely on inspect implementation for structs).

What might be a solution is to write a helper function that normalises your data before comparison (e.g. `#Decimal<1.0>` is normalised to `#Decimal<1>`), compare it, and then the rest of ExUnit works as usual.

---

regarding overriding `==/2`, not that I recommend it, but have you tried a recursive implementation? This seems to work for simple cases:

```elixir
defmodule FooTest do
  use ExUnit.Case
  import Kernel, except: [==: 2]

  def [l | ls] == [r | rs], do: l == r and ls == rs
  def (%Decimal{} = l) == (%Decimal{} = r), do: Decimal.equal?(l, r)
  def l == r, do: :erlang.==(l, r)

  test "greets the world" do
    assert [Decimal.new(1.0), Decimal.new(2)] == [Decimal.new(1), Decimal.new(2.0)]
  end
end
```

**Comment by IcyEagle** [comment]
Thank you @wojtekmach!

By the way I see recursive calls of Decimal.reduce/2 with operator overriding like a good solution for the purpose.

**Comment by wojtekmach** [comment]
> reduce/2 casts zero value to -0 (minus zero) for some reason
> replace it with a positive zero instead

@IcyEagle could you double-check? Seems to work as expected for me:

```elixir
iex(1)> Decimal.reduce(Decimal.new(0))
#Decimal<0>
```

**Comment by IcyEagle** [comment]
@wojtekmach I was surprised by that and in fact I can't reproduce it with a simple example like yours. I'll investigate my complex transformations and provide details a bit later.

**Comment by IcyEagle** [comment]
I opened related issue #95.
