### ISSUE TITLE
How to format a number to a certain precision?

### ISSUE THREAD

**Issue by GildedHonour** [ericmj/decimal#97]
Instead of 1.1 I want to print it as 1.10

Instead of 3 I want to print it as 3.00

How to do that?

**Comment by ericmj** [comment]
It is not currently possible but I am open to contributions. A new function that works like `Decimal.reduce/1` but can set a specific precision that you then pass to `Decimal.to_string(decimal, :normal)` would work.

**Comment by GildedHonour** [comment]
```
iex(6)> Decimal.new(33.553333) |> Decimal.round(2) |> Decimal.to_string()
"33.55"

iex(7)> Decimal.new(33) |> Decimal.round(2) |> Decimal.to_string()       
"33.00"

```

This will work, won't it?

**Comment by ericmj** [comment]
You are right, I forgot that `Decimal.round` also increases precision.
